### ISSUE TITLE
Real-Time Filter Suite

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#36]
_**As a user, I would like to be able to process my pictures and videos with filters in real-time.**_

Tasks to complete this story:
---------------- Release 2 ---------------- 

**Sprint 4**
- [x] Create front-end layout for b&w filter. 
- [x] Implement the b&w filter back-end. 
- [x] Create front-end layout for saturation filter.
- [x] Implement the saturation filter back-end.
- [x] UI and unit tests for b&w.
- [x] UI and unit tests for saturation.

---------------- Release 3 ---------------- 

**Sprint 5**
- [x] Create front-end icon for inverted filter.
- [x] implement inverted filter back-end.
- [x] UI and unit tests for inverted filter.

**Sprint 6**
- [x] add aqua filter.
- [x] add boards filters.
- [x] add sepia filter.
- [x] add posterize filter.

**Comment by sbouchard09** [comment]
**Acceptance Test**
This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

Step | Description | Expected Output | Actual Output | Status
---- | ----------- | --------------- | ------------- | ------
1 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
2 | The user selects the b&w option and taps the preview screen | The preview shows in greyscale | The preview shows in greyscale | pass
3 | The user taps the selfie icon | Selfie mode is activated | Selfie mode is activated | pass
4 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
5 | The user selects the solar option | The preview shows in solar mode | The preview shows in solar mode | pass |
6 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
7 | The user selects the polerize option | The preview shows in polerize mode | The preview shows in polerize mode | pass |
8 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
9 | The user selects the invert option | The preview shows in invert mode | The preview shows in invert mode | pass |
10 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
11 | The user selects the blackboard option | The preview shows in blackboard mode | The preview shows in blackboard mode | pass |
12 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
13 | The user selects the sepia option | The preview shows in sepia mode | The preview shows in sepia mode | pass |
14 | The user taps the filter icon | The filter menu appears | The filter menu appears | 
15 | The user selects the aqua option | The preview shows in aqua mode | The preview shows in aqua mode | pass |
